### ISSUE TITLE
Cannot find module './config.json'

### ISSUE THREAD

**Issue by Re4LSteaL** [jonathonor/syncBot#10]

**Comment by Re4LSteaL** [comment]
Require stack:
- C:\Users\flore\Documents\syncBot\register.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Users\flore\Documents\syncBot\register.js:3:14)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\flore\\Documents\\syncBot\\register.js'←[39m ]
}

**Comment by jonathonor** [comment]
Hi, there is a config.example.json that you will need to fill in with details for your specific server and save it as config.json

**Comment by Re4LSteaL** [comment]
Thank you very much, however, I'm getting this error. Is there a possible syntax that I'm missing?

 C:\Users\flore\Documents\syncBot>node` register.js

Started refreshing application (/) commands.
S[50035]: Invalid Form Body
guild_id[NUMBER_TYPE_COERCE]: Value "undefined" is not snowflake.
    at Q.runRequest (C:\Users\flore\node_modules\@discordjs\rest\dist\index.js:7:581)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Q.queueRequest (C:\Users\flore\node_modules\@discordjs\rest\dist\index.js:5:2942)
    at async C:\Users\flore\Documents\syncBot\register.js:43:5 {
  rawError: {
    code: 50035,
    errors: { guild_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/946367217426128906/guilds/undefined/commands',
  requestBody: { files: undefined, json: [ [Object], [Object] ] }

}

**Comment by Re4LSteaL** [comment]
Hello, thank you very much for answering my question. Sorry for being annoying, but I still have 1 more error and it's this.

C:\Users\flore\Documents\syncBot>node register.js
Started refreshing application (/) commands.
S[50001]: Missing Access
    at Q.runRequest (C:\Users\flore\node_modules\@discordjs\rest\dist\index.js:7:581)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Q.queueRequest (C:\Users\flore\node_modules\@discordjs\rest\dist\index.js:5:2942)
    at async C:\Users\flore\Documents\syncBot\register.js:43:5 {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/946367217426128906/guilds/810851584773718036/commands',
  requestBody: { files: undefined, json: [ [Object], [Object] ] }
}

**Comment by jonathonor** [comment]
Try the answer listed on this link.
https://stackoverflow.com/questions/68886388/trying-to-register-commands-discordapierror50001-missing-access

**Comment by Re4LSteaL** [comment]
Thank you very much, I got it up and running. Now I just need to figure out how to make it run 24/7
