### ISSUE TITLE
[Reverse] Bot is crashing and I don't know how to recreate it

### ISSUE THREAD

**Issue by Re4LDeaL** [jonathonor/syncBot#21]
Hello, my apologies for late report, I haven't had the time to check it. However, it seems like the bot isn't working or crashing everytime.

`node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'remove')
    at Client.<anonymous> (file:///root/DLSync/runReverse.js:497:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
root@somethingcp-11003:~/DLSync# node registerGlobal.js
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
root@somethingcp-11003:~/DLSync# node runReverse.js
syncbot ready!
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
GUILDMEMBERADD_MEMBER_FETCH Error: DiscordAPIError[10007]: Unknown Member
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'remove')
    at Client.<anonymous> (file:///root/DLSync/runReverse.js:497:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
root@somethingcp-11003:~/DLSync# node registerGlobal.js
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
root@somethingcp-11003:~/DLSync# node runReverse.js
syncbot ready!
Unable to apply action: roleAnalyze to Patreon. Member is a bot.
Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.deferReply (/root/DLSync/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:67:46)
    at roleAnalyze (file:///root/DLSync/runReverse.js:102:21)
    at file:///root/DLSync/helpers.js:15:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'InteractionAlreadyReplied'
}
exit
`

**Comment by jonathonor** [comment]
Ooh, let me take a look.
